#!/usr/bin/env python3
"""test_token_sync.py — token pipeline contract tests.

Guards the D1 regeneration moment: canonical source crackit/design_tokens.json,
codegen scripts/sync-tokens.js, output demo-video/src/light/tokens.ts.

Checks:
  1. in_sync          `node scripts/sync-tokens.js --check` exits 0 (values byte-identical)
  2. deterministic    write-mode runs reproduce the file byte-for-byte every time
  3. key_mapping      every generated T key maps 1:1 to the spec/JSON (no extra/missing keys);
                      every JSON leaf is emitted or carries a documented exclusion
  4. markers          generated file is clearly marked (DO NOT EDIT header + hand-written
                      marker), and the hand section still exports EXPO/CLAMP
  5. consumer_parity  every src/ consumer imports token values only from src/light/tokens.ts
                      and references only keys the module actually exports
  6. no_hardcoded     no string token value is hard-coded as a literal anywhere in src/
                      (except the documented test-only calibration harness)
  7. fail_loud        malformed JSON / dropped key / new unmapped key all fail with a
                      clean FATAL message and non-zero exit, writing nothing
  8. dry_run          --dry-run previews value changes without writing; exit 1 when a
                      change is pending, exit 0 when in sync

Run: python3 tests/test_token_sync.py   (from the demo-video repo root)
Exit 0 = all checks pass. stdlib only, no extra deps.
"""

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "sync-tokens.js"
JSON_PATH = ROOT.parent.parent / "crackit" / "design_tokens.json"
TS_PATH = ROOT / "src" / "light" / "tokens.ts"
SRC = ROOT / "src"

GENERATED_HEADER = "// DO NOT EDIT — generated by scripts/sync-tokens.js from crackit/design_tokens.json"
HAND_MARKER = "// === HAND-WRITTEN SECTION (not generated) ==="
HAND_EXPORTS = {"CLAMP", "EXPO"}  # hand-written, never regenerated
# Files allowed to carry exact token-value string literals (documented reasons).
LITERAL_EXEMPT = {
    "src/light/tokens.ts",  # the generated file itself
    "src/light/materialTheme.tsx",  # test-only A/B calibration harness (header says
    # "test only"); MATERIAL_B is the snapshot of the values Hamza promoted
    # into design_tokens.json — intentional duplication, not drift.
    "src/light/Showcase.tsx",  # VisualShowcase is role="demo" in the composition
    # contract (not a production render path); the literals are demo chart
    # segment data, same class as its hard-coded numeric data arrays.
}

NODE_TIMEOUT = 60


def run_node(*args, env_json=None):
    env = dict(os.environ)
    if env_json is not None:
        env["SYNC_TOKENS_JSON"] = str(env_json)
    return subprocess.run(
        ["node", str(SCRIPT), *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=NODE_TIMEOUT,
        env=env,
    )


def sha256(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def dump_spec():
    proc = run_node("--dump-spec")
    if proc.returncode != 0:
        raise RuntimeError(f"--dump-spec failed: {proc.stderr.strip()}")
    return json.loads(proc.stdout)


def generated_t_keys():
    """Parse the `name:` keys of the generated T object (before the hand marker)."""
    text = TS_PATH.read_text()
    gen = text.split(HAND_MARKER)[0]
    m = re.search(r"export const T = \{(.*?)\} as const;", gen, re.S)
    if not m:
        raise RuntimeError("generated T object not found in tokens.ts")
    keys = re.findall(r"^  (\w+):", m.group(1), re.M)
    if len(keys) != len(set(keys)):
        raise RuntimeError(f"duplicate keys in generated T object: {keys}")
    return keys


def json_lookup(doc, dotted):
    v = doc
    for k in dotted.split("."):
        v = v[k]
    return v


def json_leaves(o, prefix=""):
    if isinstance(o, dict):
        for k, v in o.items():
            yield from json_leaves(v, f"{prefix}.{k}" if prefix else k)
    else:
        yield prefix


def emitted_string_values(spec, doc):
    """The string token values consumers receive (numbers excluded: ordinary
    numbers can't be distinguished from literals, so they aren't enforceable)."""
    vals = {}
    for f in spec["fields"]:
        if f["composed"]:
            fam = json_lookup(doc, "typography.primary_family")
            fb = json_lookup(doc, "typography.fallback_family")
            vals[f["ts_name"]] = f"'{fam}', {fb}"
        else:
            v = json_lookup(doc, f["json_paths"][0])
            if isinstance(v, str):
                vals[f["ts_name"]] = v
    return vals


def src_files():
    out = []
    for p in SRC.rglob("*"):
        if p.suffix not in (".ts", ".tsx"):
            continue
        rel = p.relative_to(ROOT).as_posix()
        if "_retired" in rel.split("/"):
            continue
        out.append(p)
    return sorted(out)


def import_locals(text):
    """local name -> True for every binding imported from a *tokens module."""
    locals_ = set()
    for names, mod in re.findall(
        r'import\s*\{([^}]*)\}\s*from\s*["\']([^"\']*tokens)["\']', text
    ):
        for part in names.split(","):
            part = part.strip()
            if not part:
                continue
            m = re.match(r"(\w+)\s+as\s+(\w+)", part)
            locals_.add(m.group(2) if m else part)
    return locals_


RESULTS = []


def check(name):
    def deco(fn):
        def wrapper():
            try:
                detail = fn() or ""
                RESULTS.append((name, True, detail))
            except Exception as e:  # noqa: BLE001 - report any failure plainly
                RESULTS.append((name, False, str(e)))
        return wrapper()
    return deco


@check("1_in_sync")
def _():
    proc = run_node("--check")
    if proc.returncode != 0:
        raise RuntimeError(f"--check exited {proc.returncode}: {proc.stderr.strip()[:500]}")
    return "byte-identical to generator output"


@check("2_deterministic")
def _():
    hashes = [sha256(TS_PATH)]
    for _ in range(3):
        proc = run_node()
        if proc.returncode != 0:
            raise RuntimeError(f"write mode failed: {proc.stderr.strip()[:300]}")
        hashes.append(sha256(TS_PATH))
    if len(set(hashes)) != 1:
        raise RuntimeError(f"non-deterministic output: {hashes}")
    return f"4 runs, sha256 {hashes[0][:16]}… identical"


@check("3_key_mapping_1to1")
def _():
    spec = dump_spec()
    doc = json.loads(JSON_PATH.read_text())
    spec_names = [f["ts_name"] for f in spec["fields"]]
    gen_keys = generated_t_keys()
    if set(spec_names) != set(gen_keys):
        raise RuntimeError(
            f"spec/generated key mismatch: spec-only={set(spec_names) - set(gen_keys)}, "
            f"generated-only={set(gen_keys) - set(spec_names)}"
        )
    if len(spec_names) != len(set(spec_names)):
        raise RuntimeError("duplicate ts_name in spec")
    # every spec path resolves in the canonical JSON
    for f in spec["fields"]:
        for p in f["json_paths"]:
            json_lookup(doc, p)
    # every JSON leaf is emitted or documented-excluded (cross-checks the
    # generator's own fail-closed coverage map from the test side)
    mapped = set(spec["fields"][i]["json_paths"][0] for i in range(len(spec["fields"])))
    mapped |= {p for f in spec["fields"] for p in f["json_paths"]} | {"version"}
    uncovered = [
        p
        for p in json_leaves(doc)
        if p not in mapped
        and p not in spec["excluded_exact"]
        and not any(p.startswith(x) for x in spec["excluded_prefix"])
    ]
    if uncovered:
        raise RuntimeError(f"JSON leaves with no mapping/exclusion: {uncovered}")
    return f"{len(gen_keys)} keys map 1:1; all {sum(1 for _ in json_leaves(doc))} JSON leaves covered"


@check("4_markers")
def _():
    text = TS_PATH.read_text()
    lines = text.split("\n")
    if lines[0] != GENERATED_HEADER:
        raise RuntimeError(f"line 1 is not the generated header: {lines[0][:80]!r}")
    if HAND_MARKER not in text:
        raise RuntimeError("hand-written section marker missing")
    gen, hand = text.split(HAND_MARKER, 1)
    if "} as const;" not in gen:
        raise RuntimeError("generated T object not closed with '} as const;'")
    for name in HAND_EXPORTS:
        if f"export const {name}" not in hand:
            raise RuntimeError(f"hand-written export {name} missing after marker")
    if GENERATED_HEADER in hand:
        raise RuntimeError("generated header leaked into the hand-written section")
    return "header + marker present; EXPO/CLAMP preserved in hand section"


@check("5_consumer_parity")
def _():
    spec = dump_spec()
    allowed = {f["ts_name"] for f in spec["fields"]} | HAND_EXPORTS
    problems = []
    consumers = 0
    for p in src_files():
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text()
        if re.search(r'from\s*["\'][^"\']*design_tokens', text):
            problems.append(f"{rel}: reads design_tokens.json directly")
            continue
        locals_ = import_locals(text)
        if not locals_:
            continue
        consumers += 1
        for local in locals_:
            for key in re.findall(rf"(?<![\w$]){re.escape(local)}\.(\w+)", text):
                if key not in allowed:
                    problems.append(f"{rel}: {local}.{key} is not an exported token")
    if problems:
        raise RuntimeError("; ".join(problems[:10]))
    if consumers == 0:
        raise RuntimeError("no token consumers found under src/ — scan is broken")
    return f"{consumers} consumers, all resolve to exported keys"


@check("6_no_hardcoded_token_literals")
def _():
    spec = dump_spec()
    doc = json.loads(JSON_PATH.read_text())
    values = emitted_string_values(spec, doc)
    lit_re = re.compile(r'"(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\'')
    problems = []
    for p in src_files():
        rel = p.relative_to(ROOT).as_posix()
        if rel in LITERAL_EXEMPT:
            continue
        for i, line in enumerate(p.read_text().split("\n"), 1):
            for m in lit_re.finditer(line):
                inner = m.group(0)[1:-1]
                for name, val in values.items():
                    if inner == val:
                        problems.append(f"{rel}:{i}: literal duplicates T.{name}")
    if problems:
        raise RuntimeError("; ".join(problems[:10]))
    return f"{len(values)} string token values; no hard-coded duplicates in src/"


@check("7_fail_loud")
def _():
    doc = json.loads(JSON_PATH.read_text())
    before = sha256(TS_PATH)
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        bad = td / "bad.json"
        bad.write_text("{not valid json")
        proc = run_node("--check", env_json=bad)
        if proc.returncode == 0 or "FATAL" not in proc.stderr:
            raise RuntimeError("malformed JSON did not fail loudly")

        drop = td / "drop.json"
        d = json.loads(json.dumps(doc))
        del d["colors"]["canvas"]
        drop.write_text(json.dumps(d))
        proc = run_node(env_json=drop)
        if proc.returncode == 0 or "missing key 'colors.canvas'" not in proc.stderr:
            raise RuntimeError("dropped key did not fail loudly")

        new = td / "new.json"
        d = json.loads(json.dumps(doc))
        d["colors"]["brand_new"] = "#000000"
        new.write_text(json.dumps(d))
        proc = run_node(env_json=new)
        if proc.returncode == 0 or "no FIELDS mapping" not in proc.stderr:
            raise RuntimeError("new unmapped key did not fail loudly")
    if sha256(TS_PATH) != before:
        raise RuntimeError("a failing run wrote to tokens.ts")
    return "malformed/dropped/new-key all exit non-zero with FATAL; nothing written"


@check("8_dry_run")
def _():
    doc = json.loads(JSON_PATH.read_text())
    before = sha256(TS_PATH)
    proc = run_node("--dry-run")
    if proc.returncode != 0:
        raise RuntimeError(f"--dry-run on in-sync tree exited {proc.returncode}")
    with tempfile.TemporaryDirectory() as td:
        prev = Path(td) / "preview.json"
        d = json.loads(json.dumps(doc))
        d["colors"]["canvas"] = "#FFFFFF"
        prev.write_text(json.dumps(d))
        proc = run_node("--dry-run", env_json=prev)
        if proc.returncode != 1:
            raise RuntimeError(f"--dry-run on changed values exited {proc.returncode}, want 1")
        if '-   canvas: "#F8FAFF"' not in proc.stdout or '+   canvas: "#FFFFFF"' not in proc.stdout:
            raise RuntimeError("--dry-run did not print the expected diff")
    if sha256(TS_PATH) != before:
        raise RuntimeError("--dry-run wrote to tokens.ts")
    return "preview diff correct; file untouched in all dry-run paths"


def main():
    if not SCRIPT.exists():
        print(f"FAIL: generator missing: {SCRIPT}", file=sys.stderr)
        return 1
    if not JSON_PATH.exists():
        print(f"FAIL: canonical JSON missing: {JSON_PATH}", file=sys.stderr)
        return 1
    failed = 0
    for name, ok, detail in RESULTS:
        status = "PASS" if ok else "FAIL"
        print(f"{status} [{name}] {detail}")
        if not ok:
            failed += 1
    print(f"\n{len(RESULTS) - failed}/{len(RESULTS)} token pipeline checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
