#!/usr/bin/env node
/**
 * sync-tokens.js — codegen for src/light/tokens.ts from crackit/design_tokens.json.
 *
 * Usage:
 *   node scripts/sync-tokens.js              # regenerate src/light/tokens.ts
 *   node scripts/sync-tokens.js --check      # exit 0 "tokens in sync", exit 1 + diff to stderr (CI)
 *   node scripts/sync-tokens.js --dry-run   # preview: diff to stdout, NEVER writes; exit 0 clean / 1 would-change
 *   node scripts/sync-tokens.js --dump-spec # machine-readable mirror spec (for tests/test_token_sync.py)
 *
 * Test hook: SYNC_TOKENS_JSON overrides the JSON path (used by tests to
 * exercise malformed / dropped-key / new-key failure paths without touching
 * the real canonical JSON).
 *
 * The JSON file is resolved relative to the repo root (../../crackit/design_tokens.json
 * from demo-video/).
 *
 * Byte-determinism: the generated section must reproduce the checked-in tokens.ts
 * T-object byte-for-byte (values, camelCase names, key order, 2-space indent,
 * JSON.stringify string quoting). The hand-written section after the marker
 * (EXPO, CLAMP, ...) is preserved untouched and never regenerated.
 *
 * FAIL-CLOSED KEY POLICY:
 *   - A FIELDS key missing from the JSON -> hard error, no silent skip
 *     (lookup() throws with the exact dotted path).
 *   - A JSON leaf with NO FIELDS mapping and NO documented exclusion ->
 *     hard error listing the path. New token keys can never slip in
 *     unnoticed; extend FIELDS (emit) or EXCLUDED_* (deliberately skip)
 *     explicitly, then re-run.
 *   - EXCLUDED_EXACT / EXCLUDED_PREFIX below are the ONLY deliberately
 *     un-emitted leaves, each with its reason in the comment block.
 */

const fs = require("fs");
const path = require("path");

const MARKER = "// === HAND-WRITTEN SECTION (not generated) ===";
const GENERATED_HEADER =
  "// DO NOT EDIT — generated by scripts/sync-tokens.js from crackit/design_tokens.json";

// Ordered mirror spec: [jsonPath..., tsName]. Order == emission order ==
// the checked-in file order. font is composed (see buildFontValue).
const FIELDS = [
  [["colors", "canvas"], "canvas"],
  [["colors", "canvas_alt"], "canvasAlt"],
  [["colors", "ink"], "ink"],
  [["colors", "ink_muted"], "inkMuted"],
  [["colors", "primary"], "primary"],
  [["colors", "primary_deep"], "primaryDeep"],
  [["colors", "lavender"], "lavender"],
  [["colors", "blue_tint"], "blueTint"],
  [["colors", "success"], "success"],
  [["colors", "success_tint"], "successTint"],
  [["colors", "success_deep"], "successDeep"],
  [["colors", "warning"], "warning"],
  [["colors", "warning_tint"], "warningTint"],
  [["colors", "negative"], "negative"],
  [["colors", "negative_tint"], "negativeTint"],
  [["colors", "negative_deep"], "negativeDeep"],
  [["colors", "accent_peach"], "accentPeach"],
  [["colors", "glass_fill"], "glassFill"],
  [["colors", "glass_border"], "glassBorder"],
  [["glass", "shadow"], "glassShadow"],
  // font: composed from typography.primary_family + typography.fallback_family
  // -> "'Plus Jakarta Sans', Arial, sans-serif"
  ["__font__", "font"],
  [["radii_px", "small"], "radiusS"],
  [["radii_px", "medium"], "radiusM"],
  [["radii_px", "large"], "radiusL"],
];

// DELIBERATELY EXCLUDED JSON LEAVES (no TS consumer today — see grep over src/).
// Anything in the JSON that is neither emitted via FIELDS nor listed here is a
// HARD ERROR (fail-closed): the generator refuses to silently ignore new keys.
const EXCLUDED_EXACT = new Set([
  "name", // catalog metadata, not a token
  "glass.fill", // duplicate of colors.glass_fill — the colors.* copy is the emitted one
  "glass.border", // duplicate of colors.glass_border — the colors.* copy is the emitted one
  "glass.blur_px_default", // blur law (VISUAL_BRAIN: blur never on the reading layer)
  "glass.blur_px_max", // blur law
  "glass.foreground_blur_allowed", // blur law
]);
const EXCLUDED_PREFIX = [
  "spacing_px.", // layout spacing consumed by layout.ts, not the token module
  "motion.", // entry eases / frame counts owned by Remotion scenes directly
  "sharpness.", // resolution/render policy, not a per-component token
  "typography.weights.", // font weights referenced ad-hoc, not as tokens
];

function repoRoot() {
  // This script lives at demo-video/scripts/; the repo root is one level up.
  return path.resolve(__dirname, "..");
}

function jsonPath() {
  // Test hook first; otherwise ../../crackit/design_tokens.json relative to
  // the demo-video repo root.
  if (process.env.SYNC_TOKENS_JSON) return path.resolve(process.env.SYNC_TOKENS_JSON);
  return path.resolve(repoRoot(), "..", "..", "crackit", "design_tokens.json");
}

function tsPath() {
  return path.resolve(repoRoot(), "src", "light", "tokens.ts");
}

function lookup(json, keys) {
  let v = json;
  for (const k of keys) {
    if (v === null || typeof v !== "object" || !(k in v)) {
      throw new Error(
        `missing key '${keys.join(".")}' in design_tokens.json — ` +
          `add it to the JSON or remove it from FIELDS (no silent skips)`
      );
    }
    v = v[k];
  }
  return v;
}

function renderValue(v, label) {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number") {
    if (!Number.isFinite(v)) throw new Error(`non-finite number for '${label}'`);
    return String(v);
  }
  throw new Error(`unsupported value type for '${label}' (want string|number)`);
}

function buildFontValue(json) {
  const fam = lookup(json, ["typography", "primary_family"]);
  const fb = lookup(json, ["typography", "fallback_family"]);
  if (typeof fam !== "string" || typeof fb !== "string") {
    throw new Error("typography.primary_family/fallback_family must be strings");
  }
  return `'${fam}', ${fb}`;
}

/** Machine-readable mirror spec, also consumed by --dump-spec. */
function fieldSpec() {
  return FIELDS.map(([keys, tsName]) => ({
    ts_name: tsName,
    json_paths:
      keys === "__font__"
        ? ["typography.primary_family", "typography.fallback_family"]
        : [keys.join(".")],
    composed: keys === "__font__",
  }));
}

/** Every JSON leaf path the generator accounts for (emitted or documented). */
function mappedLeafPaths() {
  const s = new Set(["version"]); // rendered into the header comment line
  for (const [keys] of FIELDS) {
    if (keys === "__font__") {
      s.add("typography.primary_family");
      s.add("typography.fallback_family");
    } else {
      s.add(keys.join("."));
    }
  }
  return s;
}

function flattenLeaves(obj, prefix, out) {
  if (obj !== null && typeof obj === "object" && !Array.isArray(obj)) {
    for (const k of Object.keys(obj)) {
      flattenLeaves(obj[k], prefix ? `${prefix}.${k}` : k, out);
    }
  } else {
    out.push(prefix);
  }
}

/**
 * Fail-closed: every leaf in the JSON must be emitted via FIELDS or carry a
 * documented exclusion. A brand-new key with no home is a hard error, never a
 * silent skip.
 */
function validateKeyCoverage(json) {
  const mapped = mappedLeafPaths();
  const leaves = [];
  flattenLeaves(json, "", leaves);
  const unknown = leaves
    .filter(
      (p) =>
        !mapped.has(p) &&
        !EXCLUDED_EXACT.has(p) &&
        !EXCLUDED_PREFIX.some((x) => p.startsWith(x))
    )
    .sort();
  if (unknown.length > 0) {
    throw new Error(
      `design_tokens.json has ${unknown.length} key(s) with no FIELDS mapping ` +
        `and no documented exclusion: ${unknown.join(", ")} — extend FIELDS to emit ` +
        `them or EXCLUDED_* to deliberately skip them, then re-run`
    );
  }
}

function buildGenerated(json) {
  const version = String(json.version ?? "1.0");
  const lines = [
    GENERATED_HEADER,
    `// Light Premium Fintech — design tokens (from crackit/design_tokens.json v${version})`,
    "// Single source of truth for all light renderer components.",
    "export const T = {",
  ];
  for (const [keys, tsName] of FIELDS) {
    const value = keys === "__font__" ? buildFontValue(json) : lookup(json, keys);
    lines.push(`  ${tsName}: ${renderValue(value, tsName)},`);
  }
  lines.push("} as const;");
  return lines.join("\n") + "\n";
}

/**
 * Split the current tokens.ts into {generated, hand}.
 * With the marker present: everything from the marker on is the hand section.
 * First run (no marker yet): the hand section starts right after the T object,
 * which closes on the first line that is exactly "} as const;" (the EXPO/CLAMP
 * lines are single-line const declarations, never a bare "} as const;").
 */
function splitExisting(src) {
  const idx = src.indexOf(MARKER);
  if (idx >= 0) {
    // The hand section EXCLUDES the marker line itself — buildOutput
    // re-inserts exactly one marker, so re-runs stay idempotent.
    const after = src.slice(idx + MARKER.length);
    const hand = after.startsWith("\n") ? after.slice(1) : after;
    return { generated: src.slice(0, idx), hand };
  }
  const lines = src.split("\n");
  const closeIdx = lines.findIndex((l) => l === "} as const;");
  if (closeIdx < 0) {
    throw new Error(
      "cannot find the end of the generated T object " +
        "(first run expects a line that is exactly '} as const;')"
    );
  }
  const handStart = closeIdx + 1 + (lines[closeIdx + 1] === "" ? 1 : 0);
  return {
    generated: lines.slice(0, handStart).join("\n"),
    hand: lines.slice(handStart).join("\n"),
  };
}

function buildOutput(json, currentSrc) {
  const { hand } = splitExisting(currentSrc);
  return buildGenerated(json) + "\n" + MARKER + "\n" + hand;
}

/** Minimal line diff for --check / --dry-run failures (no deps). */
function lineDiff(current, generated) {
  const a = current.split("\n");
  const b = generated.split("\n");
  let start = 0;
  while (start < a.length && start < b.length && a[start] === b[start]) start++;
  let endA = a.length;
  let endB = b.length;
  while (endA > start && endB > start && a[endA - 1] === b[endB - 1]) {
    endA--;
    endB--;
  }
  const out = [
    `--- current ${path.relative(repoRoot(), tsPath())} (lines ${start + 1}-${endA})`,
    `+++ regenerated (lines ${start + 1}-${endB})`,
  ];
  for (let i = start; i < endA; i++) out.push(`- ${a[i]}`);
  for (let i = start; i < endB; i++) out.push(`+ ${b[i]}`);
  return out.join("\n");
}

function readJson(jp) {
  try {
    return JSON.parse(fs.readFileSync(jp, "utf8"));
  } catch (e) {
    throw new Error(`cannot read/parse ${jp}: ${e.message}`);
  }
}

function main() {
  const args = process.argv.slice(2);
  const jp = jsonPath();
  const tp = tsPath();

  if (args.includes("--dump-spec")) {
    const json = readJson(jp);
    validateKeyCoverage(json);
    const spec = {
      json_path: path.relative(repoRoot(), jp),
      version: String(json.version ?? "1.0"),
      fields: fieldSpec(),
      excluded_exact: [...EXCLUDED_EXACT].sort(),
      excluded_prefix: [...EXCLUDED_PREFIX],
    };
    console.log(JSON.stringify(spec, null, 2));
    return;
  }

  const json = readJson(jp);
  validateKeyCoverage(json);
  const current = fs.readFileSync(tp, "utf8");
  const out = buildOutput(json, current);

  if (args.includes("--check")) {
    if (out === current) {
      console.log("tokens in sync");
      return;
    }
    console.error("tokens OUT OF SYNC — run `node scripts/sync-tokens.js` to regenerate\n");
    console.error(lineDiff(current, out));
    process.exit(1);
  }

  if (args.includes("--dry-run")) {
    if (out === current) {
      console.log("dry-run: tokens in sync — no changes would be written");
      return;
    }
    console.log("dry-run: the following changes WOULD be written (file untouched):\n");
    console.log(lineDiff(current, out));
    console.log(
      "\nreview the diff above, then run `node scripts/sync-tokens.js` to apply"
    );
    process.exit(1);
  }

  fs.writeFileSync(tp, out, "utf8");
  console.log(`wrote ${path.relative(repoRoot(), tp)} (${out.length} bytes)`);
}

try {
  main();
} catch (e) {
  console.error(`sync-tokens: FATAL: ${e.message}`);
  process.exit(2);
}
